### ISSUE TITLE
geotag bug

### ISSUE THREAD

**Issue by Rainerino** [Rainerino/sky_eye#1]
#Run unittest output:
```python
...EE.........
======================================================================
ERROR: test_read_geo_tag (__main__.TestGeoTag)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yiyi/Documents/github/sky_eye/GeoTag/test_geotag.py", line 117, in test_read_geo_tag
    self.assertEqual(geotag.read_geo_tag('images/Apples.jpg'),
  File "/home/yiyi/Documents/github/sky_eye/GeoTag/geotag.py", line 196, in read_geo_tag
    piexif.GPSIFD.GPSLatitudeRef, bytes('N', 'utf-8')) \
TypeError: str() takes at most 1 argument (2 given)

======================================================================
ERROR: test_write_geo_tag (__main__.TestGeoTag)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yiyi/Documents/github/sky_eye/GeoTag/test_geotag.py", line 129, in test_write_geo_tag
    self.assertEqual(geotag.read_geo_tag('images/Apples_cpy.jpg'),
  File "/home/yiyi/Documents/github/sky_eye/GeoTag/geotag.py", line 196, in read_geo_tag
    piexif.GPSIFD.GPSLatitudeRef, bytes('N', 'utf-8')) \
TypeError: str() takes at most 1 argument (2 given)

----------------------------------------------------------------------
Ran 14 tests in 1.500s

FAILED (errors=2)
```

After change:
```python
    try: 
        lat_ref = exif_dict['GPS'].get(
                  piexif.GPSIFD.GPSLatitudeRef, bytes('N', 'utf-8')) \
                  .decode('utf-8')
        lat = lat_dms_to_dec(exif_dict['GPS'][piexif.GPSIFD.GPSLatitude],
                             lat_ref)
    except KeyError:
        lat = None

    try:
        lon_ref = exif_dict['GPS'].get(
                  piexif.GPSIFD.GPSLongitudeRef, bytes('E', 'utf-8')) \
                  .decode('utf-8')
        lon = lon_dms_to_dec(exif_dict['GPS'][piexif.GPSIFD.GPSLongitude],
                             lon_ref)
    except KeyError:
        lon = None
```

to 
```python

    try: 
        lat_ref = exif_dict['GPS'].get(
                  piexif.GPSIFD.GPSLatitudeRef, bytes('N')) \
                  .decode('utf-8')
        lat = lat_dms_to_dec(exif_dict['GPS'][piexif.GPSIFD.GPSLatitude],
                             lat_ref)
    except KeyError:
        lat = None

    try:
        lon_ref = exif_dict['GPS'].get(
                  piexif.GPSIFD.GPSLongitudeRef, bytes('E')) \
                  .decode('utf-8')
        lon = lon_dms_to_dec(exif_dict['GPS'][piexif.GPSIFD.GPSLongitude],
                             lon_ref)
    except KeyError:
        lon = None
```

The error went away. I dont know why that was a problem, but the image I used are first tagged geotag.write(), and then read() from to tag other newly created images. 

After I fixed it, unittest still fails:

```python
...FF.........
======================================================================
FAIL: test_read_geo_tag (__main__.TestGeoTag)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yiyi/Documents/github/sky_eye/GeoTag/test_geotag.py", line 118, in test_read_geo_tag
    (49.0278408, -122.7727156, 30, None))
AssertionError: Tuples differ: (49.0166667, -122.7666667, 30.... != (49.0278408, -122.7727156, 30,...

First differing element 0:
49.0166667
49.0278408

- (49.0166667, -122.7666667, 30.0, None)
+ (49.0278408, -122.7727156, 30, None)

======================================================================
FAIL: test_write_geo_tag (__main__.TestGeoTag)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/yiyi/Documents/github/sky_eye/GeoTag/test_geotag.py", line 130, in test_write_geo_tag
    (-49.9120223, -98.2690366, 261.64, None))
AssertionError: Tuples differ: (-49.9, -98.2666667, 261.0, No... != (-49.9120223, -98.2690366, 261...

First differing element 0:
-49.9
-49.9120223

- (-49.9, -98.2666667, 261.0, None)
?                 ---      ^

+ (-49.9120223, -98.2690366, 261.64, None)
?       ++++++        +++        ^^


----------------------------------------------------------------------
Ran 14 tests in 1.309s

FAILED (failures=2)
```

**Comment by Rainerino** [comment]
@Rainerino add python 3.5 to requirement

**Comment by Rainerino** [comment]
use python 3.5
